### SET

* Set is a unordered, unindexed type of data values
* set contains only unique elements
* Set doesnot allows any duplicate values

In [18]:
# creating a set
s={10,20,30,40,50,10,20}
print(s,type(s))

{50, 20, 40, 10, 30} <class 'set'>


In [19]:
s[0]  # can't access elements of set by using index

TypeError: 'set' object is not subscriptable

In [20]:
print(dir(s),end=" ")

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update'] 

In [21]:
s

{10, 20, 30, 40, 50}

In [22]:
s.add(60)
s

{10, 20, 30, 40, 50, 60}

In [23]:
s.update({70,80,90})
s

{10, 20, 30, 40, 50, 60, 70, 80, 90}

In [24]:
s.remove(80)
s

{10, 20, 30, 40, 50, 60, 70, 90}

In [25]:
s.pop()
s

{10, 20, 30, 40, 50, 60, 90}

In [7]:
s.clear()

In [8]:
s

set()

In [30]:
# union()

s1={1,2,3,4}
s2={3,4,5,6,7}
s1.union(s2)       # all values from both sets

{1, 2, 3, 4, 5, 6, 7}

In [31]:
s1.intersection(s2)  #common values from both sets

{3, 4}

In [32]:
s1={1,2,3,4}
s2={3,4,5,6,7}
s1.symmetric_difference(s2)

{1, 2, 5, 6, 7}

In [33]:
s2.symmetric_difference(s1)

{1, 2, 5, 6, 7}

In [34]:
s3={10,20,30}
s4={10,20,30,40,50}
s3.issubset(s4)

True

In [35]:
s4.issuperset(s3)

True

In [36]:
s={1,2,3}
s2=s.copy()
s2

{1, 2, 3}

### Functions

* Function is a block of statements , which is used to perform a specific task
* Funtions are 2 types
    * 1. In-Built functions
    * 2. User-defined functions

In [37]:
import os
os.getcwd()

'C:\\Users\\apssdc\\OneDrive\\Desktop\\DATA ANALYSIS WORKSHOP'

In [38]:
import math
math.pi

3.141592653589793

In [39]:
print(dir(math),end=" ")

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp'] 

In [42]:
# write a program to find square root of a given number

import math
num=int(input("enter a number: "))
print(num,type(num))
res=math.sqrt(num)
print("square root of the given number is: ",res)

enter a number: 144
144 <class 'int'>
square root of the given number is:  12.0


In [43]:
from math import *

In [44]:
pow(4,20)

1099511627776.0

In [45]:
ceil(90.8)

91

In [46]:
floor(90.8)

90

### user defined functions
* Functions which are defined by user, called as user defined functions

* Syntax: def function-name():
                * statements

In [49]:
# write a function to check whether the given number 
# is even or odd
def is_Even():
    n=int(input("enter a number: "))
    if n%2==0:
        print("Even number")
    else:
        print("Odd number")
is_Even()  # calling the function by it's name

enter a number: 98
Even number


In [50]:
# write a function to find cube of a given number
def cube():
    n=int(input("enter a number: "))
    res=n**3
    print("cube of a given number is: ",res)
cube()

enter a number: 5
cube of a given number is:  125


### Data Analysis

* Data is facts and statistics collected together for reference or analysis

* Data Analysis is the process of obtaining raw data and subsequently converting into information, useful for decision making by the user

#### Data Collection
* 1.Primary data:
        * Data which is collected by researchhimself/herself
        * Real time data
        * EX: Surveys, experiments, personal interviews
        * Expensive and takes long time
* 2.Secondary Data:
        * Data , which is collected by some one else earlier
        * Past data
        * Books,Websites etc..
        * Economic and takes less time
     
#### Types of data:
* 1.Structured data: rows/columns ex: excel,.csv
* 2. Unstructured data: image,audio,video,log files
* 3. Semi structured data: json,xml files

### Numpy
* Numpy stands for numerical python
* Used to work with arrays
* Numpy has large set of functioning tools to work with arrays

In [2]:
import numpy as np

In [3]:
np.__version__

'1.23.5'

In [4]:
lis=[1,2,3,4,5]
lis+10   # element wise operation not possible in lists

TypeError: can only concatenate list (not "int") to list

In [5]:
# creating array using numpy
lis=[1,2,3,4,5]
ar=np.array(lis)
ar

array([1, 2, 3, 4, 5])

In [6]:
ar+10

array([11, 12, 13, 14, 15])

In [7]:
print(ar.ndim)  # no of dimensions of array
print(ar.dtype)  # data type of array
print(ar.shape)  # shape of array
print(ar.size)  # size of array
print(ar.itemsize)  # item size of array

1
int32
(5,)
5
4


In [12]:
### accessing using index forward index, backward index
print(ar[0])
print(ar[1])
print(ar[2])
print(ar[3])
print(ar[4])

1
2
3
4
5


In [16]:
print(ar[-1])
print(ar[-2])
print(ar[-3])
print(ar[-4])

5
4
3
2


In [18]:
# slicing  [start:end:step]
print(ar[::2])
print(ar[::-1])  # reverse of an array
print(ar[1::2])

[1 3 5]
[5 4 3 2 1]
[2 4]


In [19]:
print(dir(ar),end=" ")

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '

In [22]:
# linspace()
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [23]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [25]:
np.ones(5)  # size

array([1., 1., 1., 1., 1.])

In [26]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.diag([3,4,5])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [32]:
np.full([2,3],80)   # (2,3)->no of rows/cols , fillvalue=80

array([[80, 80, 80],
       [80, 80, 80]])

In [33]:
b=np.array([10,20,30,40,50],dtype="complex")
b

array([10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j, 50.+0.j])

In [34]:
np.array([12,90.8,"hello",76.5,"world"])

array(['12', '90.8', 'hello', '76.5', 'world'], dtype='<U32')

### Range() and arange()
* arange() belongs to numpy

In [38]:
# creating array using range()
c=np.array(range(1,11))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
c=np.array(range(11,21))
c

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
c=np.array(range(11,21,2))
c

array([11, 13, 15, 17, 19])

In [41]:
ar=np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
odd=np.arange(1,100,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [43]:
ar=np.arange(200,500,5)
ar

array([200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260,
       265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320, 325,
       330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385, 390,
       395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450, 455,
       460, 465, 470, 475, 480, 485, 490, 495])

In [44]:
# random()
import random

In [45]:
np.random.random()

0.950981853181719

In [46]:
np.random.randn()

1.0964783351044787

In [49]:
ar=np.random.randint(1,100,10)
ar

array([48, 10, 83, 10, 21, 82, 37, 31, 45,  7])

In [53]:
ar=np.random.randint(1,100,20)
print(ar,type(ar))
print(ar.ndim)
b=ar.reshape(4,5)  # reshaping 1D array into 2D array
print(b)
print(b.ndim)

[30 67 63 28 25 42 45 37 87 57 98 79 80 26 93 40 41 40  9 75] <class 'numpy.ndarray'>
1
[[30 67 63 28 25]
 [42 45 37 87 57]
 [98 79 80 26 93]
 [40 41 40  9 75]]
2


In [55]:
c=np.random.randint(11,51,16)
c.reshape(4,4)

array([[14, 40, 16, 25],
       [12, 48, 48, 22],
       [36, 17, 13, 45],
       [20, 41, 37, 21]])

In [56]:
c.reshape(8,2)

array([[14, 40],
       [16, 25],
       [12, 48],
       [48, 22],
       [36, 17],
       [13, 45],
       [20, 41],
       [37, 21]])

In [57]:
c.reshape(2,8)

array([[14, 40, 16, 25, 12, 48, 48, 22],
       [36, 17, 13, 45, 20, 41, 37, 21]])

In [58]:
c.reshape(-1,4)

array([[14, 40, 16, 25],
       [12, 48, 48, 22],
       [36, 17, 13, 45],
       [20, 41, 37, 21]])

In [59]:
c.reshape(2,-1)

array([[14, 40, 16, 25, 12, 48, 48, 22],
       [36, 17, 13, 45, 20, 41, 37, 21]])

In [62]:
d=c.reshape(2,2,4)  # x,y,z 3D array
print(d)
print(d.ndim)

[[[14 40 16 25]
  [12 48 48 22]]

 [[36 17 13 45]
  [20 41 37 21]]]
3


In [64]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
np.vstack((a,b))  # vertical stacking

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
np.hstack((a,b))  # horizontal stacking

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
def grt(a,b):
    if a>b:
        return a
    else:
        return b
grt(90,76)

90

In [67]:
grt([10,97,85],[90,34,100])

[90, 34, 100]

In [68]:
vgrt=np.vectorize(grt)

In [69]:
vgrt([10,97,85],[90,34,100])

array([ 90,  97, 100])

### ravel(), flatten() 
* to convert n-dimensional array into 1 dimensional array

In [79]:
l1=[10,20,30]
l2=[40,50,60]
a=np.array([l1,l2])
print(a,a.ndim)
b=a.flatten()  # converting 2D into 1D array
print(b,b.ndim)
b[0]=100   
print(a)  # unchanged array values
print(b)

[[10 20 30]
 [40 50 60]] 2
[10 20 30 40 50 60] 1
[[10 20 30]
 [40 50 60]]
[100  20  30  40  50  60]


In [78]:
l1=[10,20,30,40]
l2=[50,60,70,80]
a=np.array([l1,l2])
b=a.ravel()
print(b,b.ndim)
b[0]=250
print(a)  # changed array values
print(b)

[10 20 30 40 50 60 70 80] 1
[[250  20  30  40]
 [ 50  60  70  80]]
[250  20  30  40  50  60  70  80]


In [94]:
# creating 2D array
b=np.array([[10,22,33],[45,55,63]])
print(b)
print(b.ndim)

[[10 22 33]
 [45 55 63]]
2


In [95]:
print(b[0][0])

10


In [96]:
print(b[0][1])

22


In [98]:
print(b[1][2])

63


In [99]:
# creating 3 Dimensional array

c=np.array([[[10,23,45],[56,78,90]],[[87,65,45],[48,76,44]]])
print(c,c.ndim)

[[[10 23 45]
  [56 78 90]]

 [[87 65 45]
  [48 76 44]]] 3


In [100]:
print(c[0][0][0])

10


In [101]:
c[0]

array([[10, 23, 45],
       [56, 78, 90]])

In [102]:
c[1]

array([[87, 65, 45],
       [48, 76, 44]])

In [103]:
c[0][1][1]

78

In [105]:
c[1][1][0]

48

In [ ]:
# create an array with 3 rows,4 cols and fill with valuen 30
# create an array with diagonal values as 10,20,30
# create an 1d array with 25 elements and reshape it as (5,5)
